#%RAML 0.8
---
title: ValidationTest
baseUri: http://test.com
version: v1

/string:
  get:
    queryParameters:
      all:
        type: string
        enum: ['aaa','bbb','ccc','dddd']
        minLength: 3
        maxLength: 5
      min:
        type: string
        minLength: 3
      max:
        type: string
        maxLength: 3
      pattern:
        type: string
      enum:
        type: string
        enum: ['aaa','bbb','ccc','dddd']

/number:
  get:
    queryParameters:
      max:
        type: number
        maximum: 10
      min:
        type: number
        minimum: 0
      number:
        type: number

/integer:
  get:
    queryParameters:
      max:
        type: number
        maximum: 10
      min:
        type: number
        minimum: 0
      integer:
        type: number

/required:
    get:
        queryParameters:
            a:
                required: true
            b:
                required: true